DROP TABLE Prestamo;
DROP TABLE Libro;
DROP TABLE Usuario;
DROP TABLE Autor;

CREATE TABLE Autor(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY, --PK
    nombre VARCHAR(30),
    apellido VARCHAR(30),
    nacionalidad VARCHAR(50),
	fecha_nacimiento DATE, --SI puede ser null
    CONSTRAINT id_Autor_PK PRIMARY KEY(id)
);
    --añadir la columna numero de premios con el default
    ALTER TABLE Autor ADD ( 
        numero_premios NUMBER(11) DEFAULT 0);

CREATE TABLE Usuario(
    id NUMBER GENERATED BY DEFAULT AS IDENTITY, --PK --GD
    nombre VARCHAR(30),
    apellido VARCHAR(30),
    direccion VARCHAR(50) NOT NULL,
    email VARCHAR(50), --unique
    telefono NUMBER(11),
    CONSTRAINT id_Usuario_PK PRIMARY KEY(id),
    CONSTRAINT email_Usuario_UQ UNIQUE(email)
);
CREATE TABLE Libro(
    isbn NUMBER(13), --PK
    titulo VARCHAR(30),
    autor NUMBER(20), --FK --si se borra nulo
	fecha_publicacion DATE,
    numero_copias NUMBER(2), -- (1-10)
	esta_descatalogado NUMBER(1), --boolean
    CONSTRAINT isbn_Libro_PK PRIMARY KEY(isbn),
    CONSTRAINT autor_Libro_FK FOREIGN KEY(autor) REFERENCES Autor(id) ON DELETE SET NULL,
    CONSTRAINT esta_descatalogado_Libro_CK CHECK (esta_descatalogado BETWEEN 0 AND 1),
    CONSTRAINT numero_copias_Libro_CK CHECK (numero_copias BETWEEN 1 AND 10)
);
CREATE TABLE Prestamo(
    libro_prestado NUMBER(13), --PK FK
    usuario NUMBER(20), --PK FK
	fecha_prestamo DATE, --PK
	fecha_devolucion DATE,
	estado_devuelto VARCHAR(1), -- Correcto / Desperfectos / Inservible”. 
    CONSTRAINT LpUFp_Prestamo_PK PRIMARY KEY(libro_prestado,usuario,fecha_prestamo),
    CONSTRAINT libro_prestado_Prestamo_FK FOREIGN KEY(libro_prestado) REFERENCES Libro(isbn),
    CONSTRAINT usuario_Prestamo_FK FOREIGN KEY(usuario) REFERENCES Usuario(id),
    CONSTRAINT estado_devuelto_Prestamo_CK CHECK (estado_devuelto IN ('C','D','I'))
);
/*
DESC Autor;
DESC Usuario;
DESC Libro;
DESC Prestamo;
*/

--añadir algunos valores
INSERT INTO Autor(nombre, apellido, nacionalidad, fecha_nacimiento)
    VALUES('Alejandra','Fernandez','su pais', DATE'2023-12-28');

INSERT INTO Usuario(nombre, apellido, direccion, email, telefono) 
    VALUES('Alejandro','Abril','su casa','nvr@educapuntomadrid.org',676898454);
INSERT INTO Usuario(nombre, apellido, direccion, email, telefono) 
    VALUES('Alex','Valsimon','la casa de al lado','123@456.789',666111666);

INSERT INTO Libro VALUES(13,'Aventuras',1,DATE'2010-5-18',1,1);
INSERT INTO Libro VALUES(14,'Aventuras 2',1,DATE'2011-5-18',1,1);

INSERT INTO Prestamo VALUES(14, 1, DATE'2023-12-26', DATE'2023-12-26', 'C');

SELECT * FROM Autor;
SELECT * FROM Usuario;
SELECT * FROM Libro;
SELECT * FROM Prestamo;
/*
--violar PK

--violar FK

--violar CK characters
INSERT INTO Prestamo(libro_prestado, usuario, fecha_prestamo, fecha_devolucion, estado_devuelto)
    VALUES(13, 1, DATE'2023-12-27', DATE'2023-12-27', 'H'); --este da error
ALTER TABLE Prestamo DISABLE CONSTRAINT estado_devuelto_Prestamo_CK; --eliminar la renstriccion
INSERT INTO Prestamo(libro_prestado, usuario, fecha_prestamo, estado_devuelto) 
    VALUES(13, 1, DATE'2023-12-26', 'H'); --este no
SELECT * FROM Prestamo;

--violar CK numeros
INSERT INTO Libro VALUES(21,'Como cocinar',1,DATE'1910-1-28',11,0); --esta da error
ALTER TABLE Libro DISABLE CONSTRAINT numero_copias_Libro_CK; --eliminar la renstriccion
INSERT INTO Libro VALUES(21,'Como cocinar',1,DATE'1910-1-28',11,0); --este no
SELECT * FROM Libro;

--violar UQ
*/

--ejercicio 3
ALTER TABLE Autor ADD 
    genero_literario VARCHAR(30);
ALTER TABLE Autor DROP COLUMN fecha_nacimiento;
ALTER TABLE Autor MODIFY nacionalidad
    VARCHAR(50) NOT NULL;

DESC Autor;
SELECT * FROM Autor;