--ejercicio 0
CREATE TABLE departamento( 
    nombre VARCHAR(30) 
    );
CREATE TABLE proyecto( 
    num NUMBER GENERATED BY DEFAULT AS IDENTITY,  
	presupuesto NUMBER(11,2) 
    );
CREATE TABLE vehiculo( 
    matricula VARCHAR(8),  
    marca VARCHAR(30) 
    );
CREATE TABLE empleado( 
    dni VARCHAR(10),  
    nombre VARCHAR(30),  
    direccion VARCHAR(50),  
    departamento VARCHAR(30) 
    );
DROP TABLE departamento;
DROP TABLE proyecto;
DROP TABLE vehiculo;
DROP TABLE empleado;

--ejercicio 1
CREATE TABLE Alumno( 
    id_alumno NUMBER GENERATED BY DEFAULT AS IDENTITY,  
    nombre VARCHAR(30),  
    fecha_nac DATE,  
    telefono NUMBER(13) 
    );
CREATE TABLE Asignatura( 
    cod_asignatura NUMBER GENERATED BY DEFAULT AS IDENTITY,  
    nombre VARCHAR(30) 
    );
CREATE TABLE Profesor( 
    nif VARCHAR(10),  
    nombre VARCHAR(30),  
    especialidad VARCHAR(30),  
    telefono NUMBER(10) 
    );
CREATE TABLE Recibe( 
    id_alumno NUMBER(5),  
    cod_asignatura NUMBER(5),  
    curso NUMBER GENERATED BY DEFAULT AS IDENTITY 
    );
CREATE TABLE Imparte( 
    nif VARCHAR(10),  
    cod_asignatura NUMBER(5) 
    );
--ejercicio 2 
INSERT INTO Alumno(nombre,fecha_nac, telefono) VALUES('Rocio Sanz', DATE '2005-08-20', 600112233);
INSERT INTO Alumno(nombre,fecha_nac, telefono) VALUES('Alicia Perez', DATE '2006-09-10', 611223344);
SELECT * FROM Alumno;

INSERT INTO Asignatura(cod_asignatura,nombre) VALUES(100, 'Bases de Datos');
INSERT INTO Asignatura(cod_asignatura,nombre) VALUES(102, 'Programación');
INSERT INTO Asignatura(nombre) VALUES('Entornos de Desarrollo');
SELECT * FROM Asignatura;

INSERT INTO Profesor(nif, nombre, especialidad, telefono) VALUES('1000000A', 'Ignacio', 'Informática', 600101010);
INSERT INTO Profesor(nif, nombre, especialidad, telefono) VALUES('2000000B', 'Daniel', 'Informática', 600202020);
INSERT INTO Profesor(nif, nombre, telefono) VALUES('3000000C', 'Mónika', 600303030);
SELECT * FROM Profesor;

INSERT INTO Recibe(id_alumno, cod_asignatura) VALUES(1, 100);
INSERT INTO Recibe(id_alumno, cod_asignatura) VALUES(2, 102);
SELECT * FROM Recibe;

INSERT INTO Imparte(nif, cod_asignatura) VALUES('Daniel ', 102);
INSERT INTO Imparte(nif, cod_asignatura) VALUES('Ignacio  ', 100);
SELECT * FROM Imparte;

DROP TABLE Alumno;
DROP TABLE Asignatura;
DROP TABLE Profesor;
DROP TABLE Recibe;
DROP TABLE Imparte;
--ejercicio 3
CREATE TABLE Profesor( 
    nif VARCHAR(10),  
    nombre VARCHAR(30),  
    especialidad VARCHAR(30),  
    telefono NUMBER(10),
    estadoBaja NUMBER(1)
    );
INSERT INTO Profesor(nif, nombre, telefono, estadoBaja) VALUES('3000000C', 'Mónika', 600303030, 0);
SELECT * FROM Profesor;
DROP TABLE Profesor;
